[package]
name = "note-server"
version = "0.1.0"
edition.workspace = true

[dependencies]
note-pipelines = { path = "../note-pipelines" }
note-mcp = { path = "../note-mcp" }
axum = "0.8.9"
tokio = { version = "1.52.3", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
note-core = { path = "../note-core" }
note-embedding = { version = "0.1.0", path = "../note-embedding" }
note-storage = { version = "0.1.0", path = "../note-storage" }
anyhow = "1.0.103"

[dev-dependencies]
tempfile = "3.27.0"
